library(testthat)
library(ggdiagram)

# rectangle ----
test_that(desc = "rectangle", {
  r2 <- ob_rectangle()
  r3 <- ob_rectangle(angle = 2)
  r <- bind(c(r2,r3))
  a <- ob_point(1,2)
  expect_identical(`==`(r2,ob_rectangle()), TRUE)
  expect_identical(`==`(r2, ob_rectangle(width = 3)), FALSE)
  expect_no_error(ob_rectangle())
  expect_no_error(r2@normal_at(degree(45)))
  expect_no_error(ob_rectangle(angle = 45))
  expect_no_error(ob_rectangle(x = 3))
  expect_no_error(ob_rectangle(y = 3))
  expect_no_error(ob_rectangle(north = a))
  expect_no_error(ob_rectangle(north = a, width = 3))
  expect_no_error(ob_rectangle(north = a, height = 3))
  expect_no_error(ob_rectangle(south = a))
  expect_no_error(ob_rectangle(south = a, width = 3))
  expect_no_error(ob_rectangle(south = a, height = 3))
  expect_no_error(ob_rectangle(west = a))
  expect_no_error(ob_rectangle(west = a, width = 3))
  expect_no_error(ob_rectangle(west = a, height = 3))
  expect_no_error(ob_rectangle(east = a))
  expect_no_error(ob_rectangle(east = a, width = 3))
  expect_no_error(ob_rectangle(east = a, height = 3))
  expect_no_error(ob_rectangle(label = ob_label(c("a", 'b'))))
  expect_no_error(rotate(ob_rectangle(), theta = degree(45)))
  expect_no_error(rotate(ob_rectangle(), theta = 45))
  expect_error(ob_rectangle(vertex_radius = c(.1, .2)), "The vertex_radius property must be of length 1\\.")
  expect_identical(r2@area, 1)
  expect_identical(r2@perimeter, 4)
  expect_no_error(r2@north)
  expect_no_error(r2@south)
  expect_no_error(r2@east)
  expect_no_error(r2@west)
  expect_no_error(r2@side)
  r2@style <- ob_style(color = "red")
  expect_identical(r2@style@color, "red")
  expect_no_error(r2@normal_at(theta = 45))
  expect_no_error(r2@point_at(theta = 45))
  expect_no_error(r2@point_at(theta = NA))
  expect_no_error(r2@geom())
  expect_no_error(r2@aesthetics)
  expect_no_error(r2@bounding_box)
  expect_no_error(r2@tibble)
  expect_no_error(get_tibble(r2))
  expect_no_error(get_tibble_defaults(r2))
  expect_no_error(capture.output(print(r2), file = nullfile()))
  expect_identical(ob_rectangle(height = 1:3)[2]@height, 2L)
  expect_no_error(place(ob_rectangle(label = ob_label("A")), ob_point(2,3)))
  expect_no_error(place(ob_point(2,3), ob_rectangle()))
  expect_identical(ob_array(ob_rectangle(), k = 4)@length, 4L)

})
