library(testthat)
library(ggdiagram)

# segment ----
test_that(desc = "segment", {
  # segment
  p1 <- ob_point(0, 3)
  p2 <- ob_point(1, 1)
  p3 <- ob_point(2, 5)
  s1 <- ob_segment(p1, p2)
  s2 <- ob_segment(p2, p3, label = ob_label("A"))
  s <- bind(c(s1,s2))
  expect_identical(nudge(s1, 1, 1),
                   ob_segment(ob_point(1, 4),
                              ob_point(2, 2)))
  expect_identical(nudge(s1, x =  1), s1 + ob_point(1, 0))
  expect_identical(nudge(s1, y =  1), s1 + ob_point(0, 1))
  expect_identical(nudge(s1), s1)
  expect_identical(nudge(s1, p3, 1), s1 + (p3 + 1))
  expect_identical(nudge(s1, p3), s1 + p3)
  expect_no_error(`+`(s1,s2))
  expect_identical(`==`(s1,s1), TRUE)
  expect_no_error(capture.output(print(s1), file = nullfile()))
  expect_identical(s1@length, 1L)
  expect_no_error(s1@bounding_box)
  expect_no_error(s2@geom())
  expect_no_error(s1@hatch())
  expect_identical(s1@midpoint(), midpoint(s1))
  expect_no_error(s1@nudge(1,1))
  expect_no_error(s1@aesthetics)
  expect_no_error(s1@tibble)
  expect_no_error(get_tibble_defaults(s1))
  expect_no_error(get_tibble(s1))
  expect_no_error(as.geom(s1))
  expect_equal(s1@length, 1)
  expect_equal(s1@distance, distance(s1))
  expect_equal(s1@line@intercept, 3)
  expect_equal(s[2], s2)
  expect_no_error(ob_segment(p1, p2))
  expect_no_error(ob_segment(x = 1, xend = 2, y = 3, yend = 5))
  expect_no_error(ob_segment(x = 1, y = 3, yend = 5))
  expect_no_error(ob_segment(xend = 1, y = 3, yend = 5))
  expect_no_error(ob_segment(x = 1, xend = 2, yend = 5))
  expect_no_error(ob_segment(x = 1, y = 3, xend = 2))
  expect_error(ob_segment(), "p1 must be a ob_point object with one or more points\\.")
  expect_error(ob_segment(p1), "If p2 is missing, p1 must be a ob_point object with multiple points\\.")
  expect_no_error(ob_segment(ob_point(1:3,3)))
  expect_no_error(ob_segment(p1, p2, label = ob_label("3")))
  expect_no_error(ob_segment(p1, p2, label = ob_label(c("3", "A"))))
  expect_no_error(rotate(ob_segment(p1, p2), theta = 45))

  s2 <- ob_segment(ob_point(1:2, 1), ob_point(1:2, 2), id = c("A", "B"))
  sB <- ob_segment(ob_point(2, 1), ob_point(2, 2), id = "B")
  expect_equal(s2["B"], sB)


})
